name: Update Playlist Every Hour

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:     # Enables manual run via Action button

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # REQUIRED: allows pushing to the repo

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: pip install python-dotenv requests

      - name: ⚙️ Run update script
        run: python update_script.py

      - name: 🧪 Show output (debug)
        run: |
          ls -l jiotv.m3u
          head -n 10 jiotv.m3u || echo "jiotv.m3u not found"

      - name: ✅ Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add jiotv.m3u || echo "Nothing to add"
          git commit -m "Auto update jiotv.m3u" || echo "No changes"

      - name: 📤 Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
